name: test-deploy-app
run-name: ${{ github.actor }} is deploying  to server
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
        SH_HOST: 'localhost'
        SH_PWD: 'Sch_t3st_#3#_pwd'
        SH_USER: 'sh_test_user'
        SH_ENV: 'test'
        SH_DATABASE: 'sh_test_db'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
          
      - run: sudo apt install mysql-server -y
      - run: mysql --version
      - run: ls
      - run: sudo apt-get install libmysqlclient-dev
      - run: sudo apt-get install zlib1g-dev
      - run: pip3 install mysqlclient
      - run: pip3 install SQLAlchemy
      - run: sudo systemctl start mysql.service
      - run: echo 'show databases; exit'  | sudo mysql
      - name: start test
        run: python3 -m unittest discover
