name: test-deploy-app
run-name: ${{ github.actor }} is deploying  to server
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  run-test:
    runs-on: ubuntu-latest
    env:
        SH_HOST: 'localhost'
        SH_PWD: 'Sch_t3st_#3#_pwd'
        SH_USER: 'sh_test_user'
        SH_ENV: 'test'
        SH_DATABASE: 'sh_test_db'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - run: mysql --version
      - run: sudo apt-get install libmysqlclient-dev
      - run: sudo apt-get install zlib1g-dev
      - run: pip3 install -r requirements.txt
      - run: sudo systemctl start mysql.service
      - run: cat setup_mysql_test.sql | sudo mysql -u root --password=root
      - name: start test
        run: pytest
  deplay-app:
    runs-on: ubuntu-latest
    needs: run-test
    steps:
    - name: install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && git checkout ${{ secrets.MAIN_BRANCH }}&& find . -name '*.pyc' -delete && git add .;git commit -m 'server stuff'; git pull -f && sudo systemctl restart schoolhub.service && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
