name: test-deploy-app
run-name: ${{ github.actor }} is deploying  to server
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Start MySQL service
      run: docker-compose up -d
      working-directory: .
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: sudo apt-get install libmysqlclient-dev
    - run: sudo apt-get install zlib1g-dev
    - run: pip3 install mysqlclient
    - run: pip3 install SQLAlchemy
    - run: cat setup_mysql_test.sql | mysql -u root -ppassword
    - name: Run unittests
      run: python3 -m unittest discover
